server:
  port: 8000

api:
  key: ------
  url:
    channel: https://napi.arvancloud.com/vod/2.0/channels/
    audio: https://napi.arvancloud.com/vod/2.0/channels/
    video: https://napi.arvancloud.com/vod/2.0/channels/